vcom -work work ./add_ip.vhd
vcom -work work ./add_ip.vhd
vcom -work work ./cp_insert.vhd
vcom -work work ./d_sel.vhd
vcom -work work ./data_direction.vhd
vcom -work work ./data_out.vhd
vcom -work work ./de_map.vhd
vcom -work work ./div.vhd
vcom -work work ./div_ip.vhd
vcom -work work ./div2_ip.vhd
vcom -work work ./en_gen.vhd
vcom -work work ./fft_ctr.vhd
vcom -work work ./fft_ip.vhd
vcom -work work ./fft_ip_tb.vhd
vcom -work work ./fifo_1024.vhd
vcom -work work ./fifo_8.vhd
vcom -work work ./ifft_data_gen.vhd
vcom -work work ./ifft_ram.vhd
vcom -work work ./ifft_ram_rd_ctr.vhd
vcom -work work ./ifft_ram_wr_ctr.vhd
vcom -work work ./led.vhd
vcom -work work ./mcp_spi.vhd
vcom -work work ./mult_complex_data.vhd
vcom -work work ./mult_complex_ip.vhd
vcom -work work ./mult_ip.vhd
vcom -work work ./plc_design.vhd
vcom -work work ./pll_ip.vhd
vcom -work work ./rcv_data_process.vhd
vcom -work work ./receiver.vhd
vcom -work work ./reg_12.vhd
vcom -work work ./reg_12_en.vhd
vcom -work work ./rom_ip.vhd
vcom -work work ./rx.vhd
vcom -work work ./rx_to_tx.vhd
vcom -work work ./sop_eop_gen.vhd
vcom -work work ./spi_ctr.vhd
vcom -work work ./syn_cox.vhd
vcom -work work ./tranceiver.vhd
vcom -work work ./transfer.vhd
vcom -work work ./tx.vhd
vcom -work work ./tx_ctr.vhd
vcom -work work ./tx_data.vhd
vcom -work work ./x_cor.vhd
vcom -work work ./fft_ip.vho